# Generated by Django 3.0.8 on 2020-07-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('text', models.TextField(max_length=255)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
